LIST_=list("HelloWorld")
LIST=("HelloWorld")
print(LIST_)
print("1.Состоит ли строка из букв")
print(LIST.isalpha())
print("2.Состоит ли строка из цифр")
print(LIST.isalpha())
print("3.Состоит ли строка из цифр или букв")
print(LIST.isalnum())
print("4.Состоит ли строка из символов в нижнем регистре")
print(LIST.islower())
print("5.Состоит ли строка из символов в верхнем регистре")
print(LIST.isupper())
print("6.Состоит ли строка из неотображаемых символов")
print(LIST.isspace())
print("7.Начинаются ли слова в строке с заглавной буквы")
print(LIST.istitle())
print("8.Преобразование строки к верхнему регистру")
print(LIST.upper())
print("9.Преобразование строки к нижнему регистру")
print(LIST.lower())
print("10.Переводит первый символ строки в верхний регистр, а все остальные в нижний")
print(LIST.capitalize())
print("11. Переводит символы нижнего регистра в верхний, а верхнего – в нижний")
print(LIST.swapcase())
